version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
