blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Support
    url: "mailto:contact@aarnphm.xyz"
    about: Contact me if you have any question.
  - name: Homepage
    url: https://aarnphm.xyz
    about: Come and visit the place where I host my second brain.
